version: '3.7'

services:
  myapp:
    container_name: myapp
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - mydb

  mydb:
    image: postgres:13
    environment:
     - POSTGRES_DB=my_db
     - POSTGRES_USER=root
     - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
